name: Build README

on:
  push:
    branches: [ main ]
    paths:
      - 'sections/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Debug - List files
      run: |
        ls -la sections/
    
    - name: Combine README files
      run: |
        echo "" > README.md  # Clear the file first
        cat sections/header.md >> README.md
        echo "" >> README.md
        cat sections/feature-project.md >> README.md
        echo "" >> README.md
        cat sections/project-showcase.md >> README.md
        echo "" >> README.md
        cat sections/stats.md >> README.md
        echo "" >> README.md
        cat sections/connect.md >> README.md
        echo "" >> README.md
        cat sections/timepass.md >> README.md
    
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Update README from section files" || exit 0
        git push